// system_intel_vvp_tpg_0_intel_vvp_tpg_2451_6thenxq.v

// This file was auto-generated from intel_vvp_tpg_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module system_intel_vvp_tpg_0_intel_vvp_tpg_2451_6thenxq (
		input  wire        main_clock_clk,       //    main_clock.clk,   Clock Input
		input  wire        main_reset_reset,     //    main_reset.reset
		output wire [23:0] axi4s_vid_out_tdata,  // axi4s_vid_out.tdata
		output wire        axi4s_vid_out_tvalid, //              .tvalid
		input  wire        axi4s_vid_out_tready, //              .tready
		output wire        axi4s_vid_out_tlast,  //              .tlast
		output wire [2:0]  axi4s_vid_out_tuser   //              .tuser
	);

	wire          main_rst_bridge_out_reset_reset;    // main_rst_bridge:out_rst -> [core_inst_0:rst, out_bridge:rst, scheduler:rst]
	wire          scheduler_axi_st_ctrl_out_tvalid;   // scheduler:axi_st_ctrl_out_tvalid -> out_bridge:axi_st_ctrl_in_tvalid
	wire    [1:0] scheduler_axi_st_ctrl_out_tuser;    // scheduler:axi_st_ctrl_out_tuser -> out_bridge:axi_st_ctrl_in_tuser
	wire          scheduler_axi_st_ctrl_out_tready;   // out_bridge:axi_st_ctrl_in_tready -> scheduler:axi_st_ctrl_out_tready
	wire   [15:0] scheduler_axi_st_ctrl_out_tdata;    // scheduler:axi_st_ctrl_out_tdata -> out_bridge:axi_st_ctrl_in_tdata
	wire          scheduler_axi_st_ctrl_out_tlast;    // scheduler:axi_st_ctrl_out_tlast -> out_bridge:axi_st_ctrl_in_tlast
	wire          scheduler_axi_st_core_cmd_0_tvalid; // scheduler:axi_st_core_cmd_0_tvalid -> core_inst_0:axi_st_cmd_tvalid
	wire          scheduler_axi_st_core_cmd_0_tready; // core_inst_0:axi_st_cmd_tready -> scheduler:axi_st_core_cmd_0_tready
	wire  [215:0] scheduler_axi_st_core_cmd_0_tdata;  // scheduler:axi_st_core_cmd_0_tdata -> core_inst_0:axi_st_cmd_tdata
	wire          core_inst_0_axi_st_data_out_tvalid; // core_inst_0:axi_st_data_out_tvalid -> out_bridge:axi_st_data_in_tvalid
	wire    [2:0] core_inst_0_axi_st_data_out_tuser;  // core_inst_0:axi_st_data_out_tuser -> out_bridge:axi_st_data_in_tuser
	wire          core_inst_0_axi_st_data_out_tready; // out_bridge:axi_st_data_in_tready -> core_inst_0:axi_st_data_out_tready
	wire   [23:0] core_inst_0_axi_st_data_out_tdata;  // core_inst_0:axi_st_data_out_tdata -> out_bridge:axi_st_data_in_tdata
	wire          core_inst_0_axi_st_data_out_tlast;  // core_inst_0:axi_st_data_out_tlast -> out_bridge:axi_st_data_in_tlast
	wire  [215:0] scheduler_axi_st_core_cmd_tdata;    // port fragment
	wire    [0:0] scheduler_axi_st_core_cmd_tvalid;   // port fragment

	intel_vvp_reset_sync #(
		.SYNC_LEN (3)
	) main_rst_bridge (
		.clk     (main_clock_clk),                  //   input,  width = 1,       clk.clk
		.in_rst  (main_reset_reset),                //   input,  width = 1,  in_reset.reset
		.out_rst (main_rst_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	intel_vvp_tpg_scheduler #(
		.EXTERNAL_MODE       (0),
		.BPS                 (8),
		.RUNTIME_CONTROL     (0),
		.ENABLE_DEBUG        (0),
		.NUM_CORES           (1),
		.ENABLE_CTRL_IN      (0),
		.FIXED_WIDTH         (64),
		.FIXED_HEIGHT        (64),
		.FIXED_R_CR          (16),
		.FIXED_G_Y           (16),
		.FIXED_B_CB          (16),
		.FIXED_INTERLACE     (0),
		.FIXED_BARS_MODE     (0),
		.FIXED_POWER_FACTOR  (16),
		.FIXED_FINE_FACTOR   (256),
		.FIXED_B_BACKGROUND  (0),
		.FIXED_G_BACKGROUND  (0),
		.FIXED_R_BACKGROUND  (0),
		.FIXED_B_FONT        (255),
		.FIXED_G_FONT        (255),
		.FIXED_R_FONT        (255),
		.FIXED_SCALE_FACTOR  (1),
		.FIXED_LOCATION_X    (0),
		.FIXED_LOCATION_Y    (0),
		.FIXED_FPS           (60),
		.CORE_COL_SPACE_0    (0),
		.CORE_PATTERN_0      (0),
		.CORE_COL_SPACE_1    (0),
		.CORE_PATTERN_1      (0),
		.CORE_COL_SPACE_2    (0),
		.CORE_PATTERN_2      (0),
		.CORE_COL_SPACE_3    (0),
		.CORE_PATTERN_3      (0),
		.CORE_COL_SPACE_4    (0),
		.CORE_PATTERN_4      (0),
		.CORE_COL_SPACE_5    (0),
		.CORE_PATTERN_5      (0),
		.CORE_COL_SPACE_6    (0),
		.CORE_PATTERN_6      (0),
		.CORE_COL_SPACE_7    (0),
		.CORE_PATTERN_7      (0),
		.PIPELINE_READY      (0),
		.SLAVE_ADDRESS_WIDTH (6)
	) scheduler (
		.clk                       (main_clock_clk),                         //   input,    width = 1,        main_clock.clk
		.rst                       (main_rst_bridge_out_reset_reset),        //   input,    width = 1,        main_reset.reset
		.axi_st_ctrl_out_tdata     (scheduler_axi_st_ctrl_out_tdata),        //  output,   width = 16,   axi_st_ctrl_out.tdata
		.axi_st_ctrl_out_tvalid    (scheduler_axi_st_ctrl_out_tvalid),       //  output,    width = 1,                  .tvalid
		.axi_st_ctrl_out_tready    (scheduler_axi_st_ctrl_out_tready),       //   input,    width = 1,                  .tready
		.axi_st_ctrl_out_tlast     (scheduler_axi_st_ctrl_out_tlast),        //  output,    width = 1,                  .tlast
		.axi_st_ctrl_out_tuser     (scheduler_axi_st_ctrl_out_tuser),        //  output,    width = 2,                  .tuser
		.axi_st_core_cmd_tdata     (scheduler_axi_st_core_cmd_tdata[215:0]), //  output,  width = 216, axi_st_core_cmd_0.tdata
		.axi_st_core_cmd_tvalid    (scheduler_axi_st_core_cmd_tvalid[0]),    //  output,    width = 1,                  .tvalid
		.axi_st_core_cmd_tready    (scheduler_axi_st_core_cmd_0_tready),     //   input,    width = 1,                  .tready
		.av_mm_slave_address       (6'b000000),                              // (terminated),                                 
		.av_mm_slave_write         (1'b0),                                   // (terminated),                                 
		.av_mm_slave_byteenable    (4'b0000),                                // (terminated),                                 
		.av_mm_slave_writedata     (32'b00000000000000000000000000000000),   // (terminated),                                 
		.av_mm_slave_read          (1'b0),                                   // (terminated),                                 
		.av_mm_slave_readdata      (),                                       // (terminated),                                 
		.av_mm_slave_readdatavalid (),                                       // (terminated),                                 
		.av_mm_slave_waitrequest   (),                                       // (terminated),                                 
		.axi_st_ctrl_in_tdata      (16'b0000000000000000),                   // (terminated),                                 
		.axi_st_ctrl_in_tvalid     (1'b0),                                   // (terminated),                                 
		.axi_st_ctrl_in_tready     (),                                       // (terminated),                                 
		.axi_st_ctrl_in_tlast      (1'b0),                                   // (terminated),                                 
		.axi_st_ctrl_in_tuser      (2'b00),                                  // (terminated),                                 
		.axi_st_mux_cmd_tdata      (),                                       // (terminated),                                 
		.axi_st_mux_cmd_tvalid     (),                                       // (terminated),                                 
		.axi_st_mux_cmd_tready     (1'b0)                                    // (terminated),                                 
	);

	intel_vvp_output_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0),
		.EXTERNAL_MODE          (0)
	) out_bridge (
		.clk                   (main_clock_clk),                     //   input,   width = 1,     main_clock.clk
		.rst                   (main_rst_bridge_out_reset_reset),    //   input,   width = 1,     main_reset.reset
		.axi_st_ctrl_in_tdata  (scheduler_axi_st_ctrl_out_tdata),    //   input,  width = 16, axi_st_ctrl_in.tdata
		.axi_st_ctrl_in_tvalid (scheduler_axi_st_ctrl_out_tvalid),   //   input,   width = 1,               .tvalid
		.axi_st_ctrl_in_tready (scheduler_axi_st_ctrl_out_tready),   //  output,   width = 1,               .tready
		.axi_st_ctrl_in_tlast  (scheduler_axi_st_ctrl_out_tlast),    //   input,   width = 1,               .tlast
		.axi_st_ctrl_in_tuser  (scheduler_axi_st_ctrl_out_tuser),    //   input,   width = 2,               .tuser
		.axi_st_data_in_tdata  (core_inst_0_axi_st_data_out_tdata),  //   input,  width = 24, axi_st_data_in.tdata
		.axi_st_data_in_tvalid (core_inst_0_axi_st_data_out_tvalid), //   input,   width = 1,               .tvalid
		.axi_st_data_in_tready (core_inst_0_axi_st_data_out_tready), //  output,   width = 1,               .tready
		.axi_st_data_in_tlast  (core_inst_0_axi_st_data_out_tlast),  //   input,   width = 1,               .tlast
		.axi_st_data_in_tuser  (core_inst_0_axi_st_data_out_tuser),  //   input,   width = 3,               .tuser
		.axi_st_ccd_out_tdata  (axi4s_vid_out_tdata),                //  output,  width = 24, axi_st_ccd_out.tdata
		.axi_st_ccd_out_tvalid (axi4s_vid_out_tvalid),               //  output,   width = 1,               .tvalid
		.axi_st_ccd_out_tready (axi4s_vid_out_tready),               //   input,   width = 1,               .tready
		.axi_st_ccd_out_tlast  (axi4s_vid_out_tlast),                //  output,   width = 1,               .tlast
		.axi_st_ccd_out_tuser  (axi4s_vid_out_tuser)                 //  output,   width = 3,               .tuser
	);

	intel_vvp_tpg_bars_algo_comp #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0),
		.TPG_CS                 ("RGB_444")
	) core_inst_0 (
		.clk                    (main_clock_clk),                     //   input,    width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),    //   input,    width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (scheduler_axi_st_core_cmd_0_tdata),  //   input,  width = 216,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi_st_core_cmd_0_tvalid), //   input,    width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi_st_core_cmd_0_tready), //  output,    width = 1,                .tready
		.axi_st_data_out_tdata  (core_inst_0_axi_st_data_out_tdata),  //  output,   width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (core_inst_0_axi_st_data_out_tvalid), //  output,    width = 1,                .tvalid
		.axi_st_data_out_tready (core_inst_0_axi_st_data_out_tready), //   input,    width = 1,                .tready
		.axi_st_data_out_tlast  (core_inst_0_axi_st_data_out_tlast),  //  output,    width = 1,                .tlast
		.axi_st_data_out_tuser  (core_inst_0_axi_st_data_out_tuser)   //  output,    width = 3,                .tuser
	);

	assign scheduler_axi_st_core_cmd_0_tdata = { scheduler_axi_st_core_cmd_tdata[215:0] };

	assign scheduler_axi_st_core_cmd_0_tvalid = { scheduler_axi_st_core_cmd_tvalid[0] };

endmodule
