// system_intel_vvp_vfb_0.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module system_intel_vvp_vfb_0 (
		input  wire        main_clock_clk,                    //           main_clock.clk,          Clock Input
		input  wire        main_reset_reset,                  //           main_reset.reset
		input  wire [23:0] axi4s_vid_in_tdata,                //         axi4s_vid_in.tdata
		input  wire        axi4s_vid_in_tvalid,               //                     .tvalid
		output wire        axi4s_vid_in_tready,               //                     .tready
		input  wire        axi4s_vid_in_tlast,                //                     .tlast
		input  wire [2:0]  axi4s_vid_in_tuser,                //                     .tuser
		output wire [23:0] axi4s_vid_out_tdata,               //        axi4s_vid_out.tdata
		output wire        axi4s_vid_out_tvalid,              //                     .tvalid
		input  wire        axi4s_vid_out_tready,              //                     .tready
		output wire        axi4s_vid_out_tlast,               //                     .tlast
		output wire [2:0]  axi4s_vid_out_tuser,               //                     .tuser
		output wire [31:0] av_mm_mem_write_host_address,      // av_mm_mem_write_host.address
		input  wire        av_mm_mem_write_host_waitrequest,  //                     .waitrequest
		output wire [2:0]  av_mm_mem_write_host_burstcount,   //                     .burstcount
		output wire        av_mm_mem_write_host_write,        //                     .write
		output wire [31:0] av_mm_mem_write_host_writedata,    //                     .writedata
		output wire [31:0] av_mm_mem_read_host_address,       //  av_mm_mem_read_host.address
		input  wire        av_mm_mem_read_host_waitrequest,   //                     .waitrequest
		output wire [2:0]  av_mm_mem_read_host_burstcount,    //                     .burstcount
		output wire        av_mm_mem_read_host_read,          //                     .read
		input  wire [31:0] av_mm_mem_read_host_readdata,      //                     .readdata
		input  wire        av_mm_mem_read_host_readdatavalid, //                     .readdatavalid
		input  wire [6:0]  av_mm_control_agent_address,       //  av_mm_control_agent.address
		input  wire        av_mm_control_agent_write,         //                     .write
		input  wire [3:0]  av_mm_control_agent_byteenable,    //                     .byteenable
		input  wire [31:0] av_mm_control_agent_writedata,     //                     .writedata
		input  wire        av_mm_control_agent_read,          //                     .read
		output wire [31:0] av_mm_control_agent_readdata,      //                     .readdata
		output wire        av_mm_control_agent_readdatavalid, //                     .readdatavalid
		output wire        av_mm_control_agent_waitrequest    //                     .waitrequest
	);

	system_intel_vvp_vfb_0_intel_vvp_vfb_2451_oqvstsi #(
		.MAX_HEIGHT             (64),
		.MAX_WIDTH              (64),
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.CLOCKS_ARE_SEPARATE    (0),
		.P_AV_MM_DATA_WIDTH     (32),
		.P_AV_MM_ADDR_WIDTH     (32),
		.WRITE_BURST_TARGET     (4),
		.READ_BURST_TARGET      (4)
	) intel_vvp_vfb_0 (
		.main_clock_clk                    (main_clock_clk),                    //   input,   width = 1,           main_clock.clk
		.main_reset_reset                  (main_reset_reset),                  //   input,   width = 1,           main_reset.reset
		.axi4s_vid_in_tdata                (axi4s_vid_in_tdata),                //   input,  width = 24,         axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (axi4s_vid_in_tvalid),               //   input,   width = 1,                     .tvalid
		.axi4s_vid_in_tready               (axi4s_vid_in_tready),               //  output,   width = 1,                     .tready
		.axi4s_vid_in_tlast                (axi4s_vid_in_tlast),                //   input,   width = 1,                     .tlast
		.axi4s_vid_in_tuser                (axi4s_vid_in_tuser),                //   input,   width = 3,                     .tuser
		.axi4s_vid_out_tdata               (axi4s_vid_out_tdata),               //  output,  width = 24,        axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (axi4s_vid_out_tvalid),              //  output,   width = 1,                     .tvalid
		.axi4s_vid_out_tready              (axi4s_vid_out_tready),              //   input,   width = 1,                     .tready
		.axi4s_vid_out_tlast               (axi4s_vid_out_tlast),               //  output,   width = 1,                     .tlast
		.axi4s_vid_out_tuser               (axi4s_vid_out_tuser),               //  output,   width = 3,                     .tuser
		.av_mm_mem_write_host_address      (av_mm_mem_write_host_address),      //  output,  width = 32, av_mm_mem_write_host.address
		.av_mm_mem_write_host_waitrequest  (av_mm_mem_write_host_waitrequest),  //   input,   width = 1,                     .waitrequest
		.av_mm_mem_write_host_burstcount   (av_mm_mem_write_host_burstcount),   //  output,   width = 3,                     .burstcount
		.av_mm_mem_write_host_write        (av_mm_mem_write_host_write),        //  output,   width = 1,                     .write
		.av_mm_mem_write_host_writedata    (av_mm_mem_write_host_writedata),    //  output,  width = 32,                     .writedata
		.av_mm_mem_read_host_address       (av_mm_mem_read_host_address),       //  output,  width = 32,  av_mm_mem_read_host.address
		.av_mm_mem_read_host_waitrequest   (av_mm_mem_read_host_waitrequest),   //   input,   width = 1,                     .waitrequest
		.av_mm_mem_read_host_burstcount    (av_mm_mem_read_host_burstcount),    //  output,   width = 3,                     .burstcount
		.av_mm_mem_read_host_read          (av_mm_mem_read_host_read),          //  output,   width = 1,                     .read
		.av_mm_mem_read_host_readdata      (av_mm_mem_read_host_readdata),      //   input,  width = 32,                     .readdata
		.av_mm_mem_read_host_readdatavalid (av_mm_mem_read_host_readdatavalid), //   input,   width = 1,                     .readdatavalid
		.av_mm_control_agent_address       (av_mm_control_agent_address),       //   input,   width = 7,  av_mm_control_agent.address
		.av_mm_control_agent_write         (av_mm_control_agent_write),         //   input,   width = 1,                     .write
		.av_mm_control_agent_byteenable    (av_mm_control_agent_byteenable),    //   input,   width = 4,                     .byteenable
		.av_mm_control_agent_writedata     (av_mm_control_agent_writedata),     //   input,  width = 32,                     .writedata
		.av_mm_control_agent_read          (av_mm_control_agent_read),          //   input,   width = 1,                     .read
		.av_mm_control_agent_readdata      (av_mm_control_agent_readdata),      //  output,  width = 32,                     .readdata
		.av_mm_control_agent_readdatavalid (av_mm_control_agent_readdatavalid), //  output,   width = 1,                     .readdatavalid
		.av_mm_control_agent_waitrequest   (av_mm_control_agent_waitrequest)    //  output,   width = 1,                     .waitrequest
	);

endmodule
