// system_intel_vvp_tpg_0.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module system_intel_vvp_tpg_0 (
		input  wire        main_clock_clk,       //    main_clock.clk,   Clock Input
		input  wire        main_reset_reset,     //    main_reset.reset
		output wire [23:0] axi4s_vid_out_tdata,  // axi4s_vid_out.tdata
		output wire        axi4s_vid_out_tvalid, //              .tvalid
		input  wire        axi4s_vid_out_tready, //              .tready
		output wire        axi4s_vid_out_tlast,  //              .tlast
		output wire [2:0]  axi4s_vid_out_tuser   //              .tuser
	);

	system_intel_vvp_tpg_0_intel_vvp_tpg_2451_b6b33ri intel_vvp_tpg_0 (
		.main_clock_clk       (main_clock_clk),       //   input,   width = 1,    main_clock.clk
		.main_reset_reset     (main_reset_reset),     //   input,   width = 1,    main_reset.reset
		.axi4s_vid_out_tdata  (axi4s_vid_out_tdata),  //  output,  width = 24, axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid (axi4s_vid_out_tvalid), //  output,   width = 1,              .tvalid
		.axi4s_vid_out_tready (axi4s_vid_out_tready), //   input,   width = 1,              .tready
		.axi4s_vid_out_tlast  (axi4s_vid_out_tlast),  //  output,   width = 1,              .tlast
		.axi4s_vid_out_tuser  (axi4s_vid_out_tuser)   //  output,   width = 3,              .tuser
	);

endmodule
