// system_intel_vvp_vfb_0_intel_vvp_vfb_2451_oqvstsi.v

// This file was auto-generated from intel_vvp_vfb_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module system_intel_vvp_vfb_0_intel_vvp_vfb_2451_oqvstsi #(
		parameter MAX_HEIGHT             = 64,
		parameter MAX_WIDTH              = 64,
		parameter BPS                    = 8,
		parameter NUMBER_OF_COLOR_PLANES = 3,
		parameter PIXELS_IN_PARALLEL     = 1,
		parameter CLOCKS_ARE_SEPARATE    = 0,
		parameter P_AV_MM_DATA_WIDTH     = 32,
		parameter P_AV_MM_ADDR_WIDTH     = 32,
		parameter WRITE_BURST_TARGET     = 4,
		parameter READ_BURST_TARGET      = 4
	) (
		input  wire        main_clock_clk,                    //           main_clock.clk,          Clock Input
		input  wire        main_reset_reset,                  //           main_reset.reset
		input  wire [23:0] axi4s_vid_in_tdata,                //         axi4s_vid_in.tdata
		input  wire        axi4s_vid_in_tvalid,               //                     .tvalid
		output wire        axi4s_vid_in_tready,               //                     .tready
		input  wire        axi4s_vid_in_tlast,                //                     .tlast
		input  wire [2:0]  axi4s_vid_in_tuser,                //                     .tuser
		output wire [23:0] axi4s_vid_out_tdata,               //        axi4s_vid_out.tdata
		output wire        axi4s_vid_out_tvalid,              //                     .tvalid
		input  wire        axi4s_vid_out_tready,              //                     .tready
		output wire        axi4s_vid_out_tlast,               //                     .tlast
		output wire [2:0]  axi4s_vid_out_tuser,               //                     .tuser
		output wire [31:0] av_mm_mem_write_host_address,      // av_mm_mem_write_host.address
		input  wire        av_mm_mem_write_host_waitrequest,  //                     .waitrequest
		output wire [2:0]  av_mm_mem_write_host_burstcount,   //                     .burstcount
		output wire        av_mm_mem_write_host_write,        //                     .write
		output wire [31:0] av_mm_mem_write_host_writedata,    //                     .writedata
		output wire [31:0] av_mm_mem_read_host_address,       //  av_mm_mem_read_host.address
		input  wire        av_mm_mem_read_host_waitrequest,   //                     .waitrequest
		output wire [2:0]  av_mm_mem_read_host_burstcount,    //                     .burstcount
		output wire        av_mm_mem_read_host_read,          //                     .read
		input  wire [31:0] av_mm_mem_read_host_readdata,      //                     .readdata
		input  wire        av_mm_mem_read_host_readdatavalid, //                     .readdatavalid
		input  wire [6:0]  av_mm_control_agent_address,       //  av_mm_control_agent.address
		input  wire        av_mm_control_agent_write,         //                     .write
		input  wire [3:0]  av_mm_control_agent_byteenable,    //                     .byteenable
		input  wire [31:0] av_mm_control_agent_writedata,     //                     .writedata
		input  wire        av_mm_control_agent_read,          //                     .read
		output wire [31:0] av_mm_control_agent_readdata,      //                     .readdata
		output wire        av_mm_control_agent_readdatavalid, //                     .readdatavalid
		output wire        av_mm_control_agent_waitrequest    //                     .waitrequest
	);

	wire         axi_st_reset_bridge_out_reset_reset;                   // axi_st_reset_bridge:out_rst -> [discard:rst, iib:rst, mm_interconnect_0:ro_reg_servicer_av_mm_master_translator_reset_reset_bridge_in_reset_reset, oib:rst, packet_reader:rst, packet_writer:rst, ro_reg_servicer:rst, scheduler:rst, snoop:rst]
	wire         scheduler_axi_st_cmd_pkt_wr_tvalid;                    // scheduler:axi_st_cmd_pkt_wr_tvalid -> packet_writer:axi_st_cmd_tvalid
	wire         scheduler_axi_st_cmd_pkt_wr_tready;                    // packet_writer:axi_st_cmd_tready -> scheduler:axi_st_cmd_pkt_wr_tready
	wire  [71:0] scheduler_axi_st_cmd_pkt_wr_tdata;                     // scheduler:axi_st_cmd_pkt_wr_tdata -> packet_writer:axi_st_cmd_tdata
	wire         packet_writer_axi_st_resp_tvalid;                      // packet_writer:axi_st_resp_tvalid -> scheduler:axi_st_resp_pkt_wr_tvalid
	wire         packet_writer_axi_st_resp_tready;                      // scheduler:axi_st_resp_pkt_wr_tready -> packet_writer:axi_st_resp_tready
	wire   [7:0] packet_writer_axi_st_resp_tdata;                       // packet_writer:axi_st_resp_tdata -> scheduler:axi_st_resp_pkt_wr_tdata
	wire         scheduler_axi_st_cmd_pkt_rd_tvalid;                    // scheduler:axi_st_cmd_pkt_rd_tvalid -> packet_reader:axi_st_cmd_tvalid
	wire         scheduler_axi_st_cmd_pkt_rd_tready;                    // packet_reader:axi_st_cmd_tready -> scheduler:axi_st_cmd_pkt_rd_tready
	wire  [71:0] scheduler_axi_st_cmd_pkt_rd_tdata;                     // scheduler:axi_st_cmd_pkt_rd_tdata -> packet_reader:axi_st_cmd_tdata
	wire         packet_reader_axi_st_resp_tvalid;                      // packet_reader:axi_st_resp_tvalid -> scheduler:axi_st_resp_pkt_rd_tvalid
	wire         packet_reader_axi_st_resp_tready;                      // scheduler:axi_st_resp_pkt_rd_tready -> packet_reader:axi_st_resp_tready
	wire   [7:0] packet_reader_axi_st_resp_tdata;                       // packet_reader:axi_st_resp_tdata -> scheduler:axi_st_resp_pkt_rd_tdata
	wire         snoop_axi_st_resp_tvalid;                              // snoop:axi_st_resp_tvalid -> scheduler:axi_st_resp_snoop_tvalid
	wire         snoop_axi_st_resp_tready;                              // scheduler:axi_st_resp_snoop_tready -> snoop:axi_st_resp_tready
	wire  [23:0] snoop_axi_st_resp_tdata;                               // snoop:axi_st_resp_tdata -> scheduler:axi_st_resp_snoop_tdata
	wire         iib_axi_st_data_out_tvalid;                            // iib:axi_st_data_out_tvalid -> discard:axi_st_data_in_tvalid
	wire   [2:0] iib_axi_st_data_out_tuser;                             // iib:axi_st_data_out_tuser -> discard:axi_st_data_in_tuser
	wire         iib_axi_st_data_out_tready;                            // discard:axi_st_data_in_tready -> iib:axi_st_data_out_tready
	wire  [23:0] iib_axi_st_data_out_tdata;                             // iib:axi_st_data_out_tdata -> discard:axi_st_data_in_tdata
	wire         iib_axi_st_data_out_tlast;                             // iib:axi_st_data_out_tlast -> discard:axi_st_data_in_tlast
	wire         discard_axi_st_data_out_tvalid;                        // discard:axi_st_data_out_tvalid -> snoop:axi_st_data_in_tvalid
	wire   [2:0] discard_axi_st_data_out_tuser;                         // discard:axi_st_data_out_tuser -> snoop:axi_st_data_in_tuser
	wire         discard_axi_st_data_out_tready;                        // snoop:axi_st_data_in_tready -> discard:axi_st_data_out_tready
	wire  [23:0] discard_axi_st_data_out_tdata;                         // discard:axi_st_data_out_tdata -> snoop:axi_st_data_in_tdata
	wire         discard_axi_st_data_out_tlast;                         // discard:axi_st_data_out_tlast -> snoop:axi_st_data_in_tlast
	wire         snoop_axi_st_data_out_tvalid;                          // snoop:axi_st_data_out_tvalid -> packet_writer:axi_st_data_in_tvalid
	wire   [2:0] snoop_axi_st_data_out_tuser;                           // snoop:axi_st_data_out_tuser -> packet_writer:axi_st_data_in_tuser
	wire         snoop_axi_st_data_out_tready;                          // packet_writer:axi_st_data_in_tready -> snoop:axi_st_data_out_tready
	wire  [23:0] snoop_axi_st_data_out_tdata;                           // snoop:axi_st_data_out_tdata -> packet_writer:axi_st_data_in_tdata
	wire         snoop_axi_st_data_out_tlast;                           // snoop:axi_st_data_out_tlast -> packet_writer:axi_st_data_in_tlast
	wire         scheduler_axi_st_cmd_discard_tvalid;                   // scheduler:axi_st_cmd_discard_tvalid -> discard:axi_st_cmd_tvalid
	wire         scheduler_axi_st_cmd_discard_tready;                   // discard:axi_st_cmd_tready -> scheduler:axi_st_cmd_discard_tready
	wire   [7:0] scheduler_axi_st_cmd_discard_tdata;                    // scheduler:axi_st_cmd_discard_tdata -> discard:axi_st_cmd_tdata
	wire         iib_axi_st_ctrl_out_tvalid;                            // iib:axi_st_ctrl_out_tvalid -> scheduler:axi_st_ctrl_in_tvalid
	wire   [1:0] iib_axi_st_ctrl_out_tuser;                             // iib:axi_st_ctrl_out_tuser -> scheduler:axi_st_ctrl_in_tuser
	wire         iib_axi_st_ctrl_out_tready;                            // scheduler:axi_st_ctrl_in_tready -> iib:axi_st_ctrl_out_tready
	wire  [15:0] iib_axi_st_ctrl_out_tdata;                             // iib:axi_st_ctrl_out_tdata -> scheduler:axi_st_ctrl_in_tdata
	wire         iib_axi_st_ctrl_out_tlast;                             // iib:axi_st_ctrl_out_tlast -> scheduler:axi_st_ctrl_in_tlast
	wire         scheduler_axi_st_ctrl_out_tvalid;                      // scheduler:axi_st_ctrl_out_tvalid -> oib:axi_st_ctrl_in_tvalid
	wire   [1:0] scheduler_axi_st_ctrl_out_tuser;                       // scheduler:axi_st_ctrl_out_tuser -> oib:axi_st_ctrl_in_tuser
	wire         scheduler_axi_st_ctrl_out_tready;                      // oib:axi_st_ctrl_in_tready -> scheduler:axi_st_ctrl_out_tready
	wire  [15:0] scheduler_axi_st_ctrl_out_tdata;                       // scheduler:axi_st_ctrl_out_tdata -> oib:axi_st_ctrl_in_tdata
	wire         scheduler_axi_st_ctrl_out_tlast;                       // scheduler:axi_st_ctrl_out_tlast -> oib:axi_st_ctrl_in_tlast
	wire         packet_reader_axi_st_data_out_tvalid;                  // packet_reader:axi_st_data_out_tvalid -> oib:axi_st_data_in_tvalid
	wire   [2:0] packet_reader_axi_st_data_out_tuser;                   // packet_reader:axi_st_data_out_tuser -> oib:axi_st_data_in_tuser
	wire         packet_reader_axi_st_data_out_tready;                  // oib:axi_st_data_in_tready -> packet_reader:axi_st_data_out_tready
	wire  [23:0] packet_reader_axi_st_data_out_tdata;                   // packet_reader:axi_st_data_out_tdata -> oib:axi_st_data_in_tdata
	wire         packet_reader_axi_st_data_out_tlast;                   // packet_reader:axi_st_data_out_tlast -> oib:axi_st_data_in_tlast
	wire         ro_reg_servicer_av_mm_master_waitrequest;              // mm_interconnect_0:ro_reg_servicer_av_mm_master_waitrequest -> ro_reg_servicer:av_mm_master_waitrequest
	wire  [31:0] ro_reg_servicer_av_mm_master_readdata;                 // mm_interconnect_0:ro_reg_servicer_av_mm_master_readdata -> ro_reg_servicer:av_mm_master_readdata
	wire   [6:0] ro_reg_servicer_av_mm_master_address;                  // ro_reg_servicer:av_mm_master_address -> mm_interconnect_0:ro_reg_servicer_av_mm_master_address
	wire   [3:0] ro_reg_servicer_av_mm_master_byteenable;               // ro_reg_servicer:av_mm_master_byteenable -> mm_interconnect_0:ro_reg_servicer_av_mm_master_byteenable
	wire         ro_reg_servicer_av_mm_master_read;                     // ro_reg_servicer:av_mm_master_read -> mm_interconnect_0:ro_reg_servicer_av_mm_master_read
	wire         ro_reg_servicer_av_mm_master_readdatavalid;            // mm_interconnect_0:ro_reg_servicer_av_mm_master_readdatavalid -> ro_reg_servicer:av_mm_master_readdatavalid
	wire         ro_reg_servicer_av_mm_master_write;                    // ro_reg_servicer:av_mm_master_write -> mm_interconnect_0:ro_reg_servicer_av_mm_master_write
	wire  [31:0] ro_reg_servicer_av_mm_master_writedata;                // ro_reg_servicer:av_mm_master_writedata -> mm_interconnect_0:ro_reg_servicer_av_mm_master_writedata
	wire  [31:0] mm_interconnect_0_scheduler_av_mm_agent_readdata;      // scheduler:av_mm_agent_readdata -> mm_interconnect_0:scheduler_av_mm_agent_readdata
	wire         mm_interconnect_0_scheduler_av_mm_agent_waitrequest;   // scheduler:av_mm_agent_waitrequest -> mm_interconnect_0:scheduler_av_mm_agent_waitrequest
	wire   [4:0] mm_interconnect_0_scheduler_av_mm_agent_address;       // mm_interconnect_0:scheduler_av_mm_agent_address -> scheduler:av_mm_agent_address
	wire         mm_interconnect_0_scheduler_av_mm_agent_read;          // mm_interconnect_0:scheduler_av_mm_agent_read -> scheduler:av_mm_agent_read
	wire   [3:0] mm_interconnect_0_scheduler_av_mm_agent_byteenable;    // mm_interconnect_0:scheduler_av_mm_agent_byteenable -> scheduler:av_mm_agent_byteenable
	wire         mm_interconnect_0_scheduler_av_mm_agent_readdatavalid; // scheduler:av_mm_agent_readdatavalid -> mm_interconnect_0:scheduler_av_mm_agent_readdatavalid
	wire         mm_interconnect_0_scheduler_av_mm_agent_write;         // mm_interconnect_0:scheduler_av_mm_agent_write -> scheduler:av_mm_agent_write
	wire  [31:0] mm_interconnect_0_scheduler_av_mm_agent_writedata;     // mm_interconnect_0:scheduler_av_mm_agent_writedata -> scheduler:av_mm_agent_writedata

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (MAX_HEIGHT != 64)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					max_height_check ( .error(1'b1) );
		end
		if (MAX_WIDTH != 64)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					max_width_check ( .error(1'b1) );
		end
		if (BPS != 8)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					bps_check ( .error(1'b1) );
		end
		if (NUMBER_OF_COLOR_PLANES != 3)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					number_of_color_planes_check ( .error(1'b1) );
		end
		if (PIXELS_IN_PARALLEL != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					pixels_in_parallel_check ( .error(1'b1) );
		end
		if (CLOCKS_ARE_SEPARATE != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					clocks_are_separate_check ( .error(1'b1) );
		end
		if (P_AV_MM_DATA_WIDTH != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					p_av_mm_data_width_check ( .error(1'b1) );
		end
		if (P_AV_MM_ADDR_WIDTH != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					p_av_mm_addr_width_check ( .error(1'b1) );
		end
		if (WRITE_BURST_TARGET != 4)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					write_burst_target_check ( .error(1'b1) );
		end
		if (READ_BURST_TARGET != 4)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					read_burst_target_check ( .error(1'b1) );
		end
	endgenerate

	intel_vvp_reset_sync #(
		.SYNC_LEN (3)
	) axi_st_reset_bridge (
		.clk     (main_clock_clk),                      //   input,  width = 1,       clk.clk
		.in_rst  (main_reset_reset),                    //   input,  width = 1,  in_reset.reset
		.out_rst (axi_st_reset_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	intel_vvp_input_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (1),
		.EXTERNAL_MODE          (0)
	) iib (
		.clk                    (main_clock_clk),                      //   input,   width = 1,      main_clock.clk
		.rst                    (axi_st_reset_bridge_out_reset_reset), //   input,   width = 1,      main_reset.reset
		.axi_st_ccd_in_tdata    (axi4s_vid_in_tdata),                  //   input,  width = 24,   axi_st_ccd_in.tdata
		.axi_st_ccd_in_tvalid   (axi4s_vid_in_tvalid),                 //   input,   width = 1,                .tvalid
		.axi_st_ccd_in_tready   (axi4s_vid_in_tready),                 //  output,   width = 1,                .tready
		.axi_st_ccd_in_tlast    (axi4s_vid_in_tlast),                  //   input,   width = 1,                .tlast
		.axi_st_ccd_in_tuser    (axi4s_vid_in_tuser),                  //   input,   width = 3,                .tuser
		.axi_st_ctrl_out_tdata  (iib_axi_st_ctrl_out_tdata),           //  output,  width = 16, axi_st_ctrl_out.tdata
		.axi_st_ctrl_out_tvalid (iib_axi_st_ctrl_out_tvalid),          //  output,   width = 1,                .tvalid
		.axi_st_ctrl_out_tready (iib_axi_st_ctrl_out_tready),          //   input,   width = 1,                .tready
		.axi_st_ctrl_out_tlast  (iib_axi_st_ctrl_out_tlast),           //  output,   width = 1,                .tlast
		.axi_st_ctrl_out_tuser  (iib_axi_st_ctrl_out_tuser),           //  output,   width = 2,                .tuser
		.axi_st_data_out_tdata  (iib_axi_st_data_out_tdata),           //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (iib_axi_st_data_out_tvalid),          //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (iib_axi_st_data_out_tready),          //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (iib_axi_st_data_out_tlast),           //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (iib_axi_st_data_out_tuser)            //  output,   width = 3,                .tuser
	);

	intel_vvp_output_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (1),
		.EXTERNAL_MODE          (0)
	) oib (
		.clk                   (main_clock_clk),                       //   input,   width = 1,     main_clock.clk
		.rst                   (axi_st_reset_bridge_out_reset_reset),  //   input,   width = 1,     main_reset.reset
		.axi_st_ctrl_in_tdata  (scheduler_axi_st_ctrl_out_tdata),      //   input,  width = 16, axi_st_ctrl_in.tdata
		.axi_st_ctrl_in_tvalid (scheduler_axi_st_ctrl_out_tvalid),     //   input,   width = 1,               .tvalid
		.axi_st_ctrl_in_tready (scheduler_axi_st_ctrl_out_tready),     //  output,   width = 1,               .tready
		.axi_st_ctrl_in_tlast  (scheduler_axi_st_ctrl_out_tlast),      //   input,   width = 1,               .tlast
		.axi_st_ctrl_in_tuser  (scheduler_axi_st_ctrl_out_tuser),      //   input,   width = 2,               .tuser
		.axi_st_data_in_tdata  (packet_reader_axi_st_data_out_tdata),  //   input,  width = 24, axi_st_data_in.tdata
		.axi_st_data_in_tvalid (packet_reader_axi_st_data_out_tvalid), //   input,   width = 1,               .tvalid
		.axi_st_data_in_tready (packet_reader_axi_st_data_out_tready), //  output,   width = 1,               .tready
		.axi_st_data_in_tlast  (packet_reader_axi_st_data_out_tlast),  //   input,   width = 1,               .tlast
		.axi_st_data_in_tuser  (packet_reader_axi_st_data_out_tuser),  //   input,   width = 3,               .tuser
		.axi_st_ccd_out_tdata  (axi4s_vid_out_tdata),                  //  output,  width = 24, axi_st_ccd_out.tdata
		.axi_st_ccd_out_tvalid (axi4s_vid_out_tvalid),                 //  output,   width = 1,               .tvalid
		.axi_st_ccd_out_tready (axi4s_vid_out_tready),                 //   input,   width = 1,               .tready
		.axi_st_ccd_out_tlast  (axi4s_vid_out_tlast),                  //  output,   width = 1,               .tlast
		.axi_st_ccd_out_tuser  (axi4s_vid_out_tuser)                   //  output,   width = 3,               .tuser
	);

	intel_vvp_vfb_scheduler #(
		.MAX_WIDTH                     (64),
		.MAX_HEIGHT                    (64),
		.PIXELS_IN_PARALLEL            (1),
		.FRAME_DROP_ENABLE             (1),
		.FRAME_REPEAT_ENABLE           (1),
		.DROP_BROKEN_FRAMES            (1),
		.MEM_BUFF_BASE_ADDR            (0),
		.MEM_BUFF_STRIDE               (268435456),
		.MEM_BUFF_LINE_STRIDE          (32768),
		.MAX_CONTROL_PACKETS           (0),
		.DROP_RPT_AUX_PKTS_WITH_FRAMES (0),
		.RUNTIME_CONTROL               (1),
		.ENABLE_DEBUG                  (0),
		.EXTERNAL_MODE                 (0),
		.PIPELINE_READY                (1)
	) scheduler (
		.clk                       (main_clock_clk),                                        //   input,   width = 1,         main_clock.clk
		.rst                       (axi_st_reset_bridge_out_reset_reset),                   //   input,   width = 1,         main_reset.reset
		.av_mm_agent_address       (mm_interconnect_0_scheduler_av_mm_agent_address),       //   input,   width = 5,        av_mm_agent.address
		.av_mm_agent_write         (mm_interconnect_0_scheduler_av_mm_agent_write),         //   input,   width = 1,                   .write
		.av_mm_agent_byteenable    (mm_interconnect_0_scheduler_av_mm_agent_byteenable),    //   input,   width = 4,                   .byteenable
		.av_mm_agent_writedata     (mm_interconnect_0_scheduler_av_mm_agent_writedata),     //   input,  width = 32,                   .writedata
		.av_mm_agent_read          (mm_interconnect_0_scheduler_av_mm_agent_read),          //   input,   width = 1,                   .read
		.av_mm_agent_readdata      (mm_interconnect_0_scheduler_av_mm_agent_readdata),      //  output,  width = 32,                   .readdata
		.av_mm_agent_readdatavalid (mm_interconnect_0_scheduler_av_mm_agent_readdatavalid), //  output,   width = 1,                   .readdatavalid
		.av_mm_agent_waitrequest   (mm_interconnect_0_scheduler_av_mm_agent_waitrequest),   //  output,   width = 1,                   .waitrequest
		.axi_st_ctrl_in_tdata      (iib_axi_st_ctrl_out_tdata),                             //   input,  width = 16,     axi_st_ctrl_in.tdata
		.axi_st_ctrl_in_tvalid     (iib_axi_st_ctrl_out_tvalid),                            //   input,   width = 1,                   .tvalid
		.axi_st_ctrl_in_tready     (iib_axi_st_ctrl_out_tready),                            //  output,   width = 1,                   .tready
		.axi_st_ctrl_in_tlast      (iib_axi_st_ctrl_out_tlast),                             //   input,   width = 1,                   .tlast
		.axi_st_ctrl_in_tuser      (iib_axi_st_ctrl_out_tuser),                             //   input,   width = 2,                   .tuser
		.axi_st_ctrl_out_tdata     (scheduler_axi_st_ctrl_out_tdata),                       //  output,  width = 16,    axi_st_ctrl_out.tdata
		.axi_st_ctrl_out_tvalid    (scheduler_axi_st_ctrl_out_tvalid),                      //  output,   width = 1,                   .tvalid
		.axi_st_ctrl_out_tready    (scheduler_axi_st_ctrl_out_tready),                      //   input,   width = 1,                   .tready
		.axi_st_ctrl_out_tlast     (scheduler_axi_st_ctrl_out_tlast),                       //  output,   width = 1,                   .tlast
		.axi_st_ctrl_out_tuser     (scheduler_axi_st_ctrl_out_tuser),                       //  output,   width = 2,                   .tuser
		.axi_st_resp_snoop_tdata   (snoop_axi_st_resp_tdata),                               //   input,  width = 24,  axi_st_resp_snoop.tdata
		.axi_st_resp_snoop_tvalid  (snoop_axi_st_resp_tvalid),                              //   input,   width = 1,                   .tvalid
		.axi_st_resp_snoop_tready  (snoop_axi_st_resp_tready),                              //  output,   width = 1,                   .tready
		.axi_st_cmd_discard_tdata  (scheduler_axi_st_cmd_discard_tdata),                    //  output,   width = 8, axi_st_cmd_discard.tdata
		.axi_st_cmd_discard_tvalid (scheduler_axi_st_cmd_discard_tvalid),                   //  output,   width = 1,                   .tvalid
		.axi_st_cmd_discard_tready (scheduler_axi_st_cmd_discard_tready),                   //   input,   width = 1,                   .tready
		.axi_st_cmd_pkt_wr_tdata   (scheduler_axi_st_cmd_pkt_wr_tdata),                     //  output,  width = 72,  axi_st_cmd_pkt_wr.tdata
		.axi_st_cmd_pkt_wr_tvalid  (scheduler_axi_st_cmd_pkt_wr_tvalid),                    //  output,   width = 1,                   .tvalid
		.axi_st_cmd_pkt_wr_tready  (scheduler_axi_st_cmd_pkt_wr_tready),                    //   input,   width = 1,                   .tready
		.axi_st_resp_pkt_wr_tdata  (packet_writer_axi_st_resp_tdata),                       //   input,   width = 8, axi_st_resp_pkt_wr.tdata
		.axi_st_resp_pkt_wr_tvalid (packet_writer_axi_st_resp_tvalid),                      //   input,   width = 1,                   .tvalid
		.axi_st_resp_pkt_wr_tready (packet_writer_axi_st_resp_tready),                      //  output,   width = 1,                   .tready
		.axi_st_cmd_pkt_rd_tdata   (scheduler_axi_st_cmd_pkt_rd_tdata),                     //  output,  width = 72,  axi_st_cmd_pkt_rd.tdata
		.axi_st_cmd_pkt_rd_tvalid  (scheduler_axi_st_cmd_pkt_rd_tvalid),                    //  output,   width = 1,                   .tvalid
		.axi_st_cmd_pkt_rd_tready  (scheduler_axi_st_cmd_pkt_rd_tready),                    //   input,   width = 1,                   .tready
		.axi_st_resp_pkt_rd_tdata  (packet_reader_axi_st_resp_tdata),                       //   input,   width = 8, axi_st_resp_pkt_rd.tdata
		.axi_st_resp_pkt_rd_tvalid (packet_reader_axi_st_resp_tvalid),                      //   input,   width = 1,                   .tvalid
		.axi_st_resp_pkt_rd_tready (packet_reader_axi_st_resp_tready)                       //  output,   width = 1,                   .tready
	);

	intel_vvp_snoop_core #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (1),
		.VVP_COUNT_MAX          (1)
	) snoop (
		.clk                    (main_clock_clk),                      //   input,   width = 1,      main_clock.clk
		.rst                    (axi_st_reset_bridge_out_reset_reset), //   input,   width = 1,      main_reset.reset
		.axi_st_resp_tdata      (snoop_axi_st_resp_tdata),             //  output,  width = 24,     axi_st_resp.tdata
		.axi_st_resp_tvalid     (snoop_axi_st_resp_tvalid),            //  output,   width = 1,                .tvalid
		.axi_st_resp_tready     (snoop_axi_st_resp_tready),            //   input,   width = 1,                .tready
		.axi_st_data_in_tdata   (discard_axi_st_data_out_tdata),       //   input,  width = 24,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (discard_axi_st_data_out_tvalid),      //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (discard_axi_st_data_out_tready),      //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (discard_axi_st_data_out_tlast),       //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (discard_axi_st_data_out_tuser),       //   input,   width = 3,                .tuser
		.axi_st_data_out_tdata  (snoop_axi_st_data_out_tdata),         //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (snoop_axi_st_data_out_tvalid),        //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (snoop_axi_st_data_out_tready),        //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (snoop_axi_st_data_out_tlast),         //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (snoop_axi_st_data_out_tuser)          //  output,   width = 3,                .tuser
	);

	intel_vvp_packet_discard #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (1)
	) discard (
		.clk                    (main_clock_clk),                      //   input,   width = 1,      main_clock.clk
		.rst                    (axi_st_reset_bridge_out_reset_reset), //   input,   width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (scheduler_axi_st_cmd_discard_tdata),  //   input,   width = 8,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi_st_cmd_discard_tvalid), //   input,   width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi_st_cmd_discard_tready), //  output,   width = 1,                .tready
		.axi_st_data_in_tdata   (iib_axi_st_data_out_tdata),           //   input,  width = 24,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (iib_axi_st_data_out_tvalid),          //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (iib_axi_st_data_out_tready),          //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (iib_axi_st_data_out_tlast),           //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (iib_axi_st_data_out_tuser),           //   input,   width = 3,                .tuser
		.axi_st_data_out_tdata  (discard_axi_st_data_out_tdata),       //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (discard_axi_st_data_out_tvalid),      //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (discard_axi_st_data_out_tready),      //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (discard_axi_st_data_out_tlast),       //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (discard_axi_st_data_out_tuser)        //  output,   width = 3,                .tuser
	);

	intel_vvp_packet_writer #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (1),
		.CLOCKS_ARE_SEPARATE    (0),
		.P_AV_MM_DATA_WIDTH     (32),
		.P_AV_MM_ADDR_WIDTH     (32),
		.BURST_TARGET           (4),
		.FIFO_DEPTH             (64),
		.ENABLE_RESPONSES       (1),
		.PACKING_LEVEL          (1),
		.DEVICE_FAMILY          ("Cyclone 10 GX")
	) packet_writer (
		.clk                      (main_clock_clk),                      //   input,   width = 1,     main_clock.clk
		.rst                      (axi_st_reset_bridge_out_reset_reset), //   input,   width = 1,     main_reset.reset
		.axi_st_cmd_tdata         (scheduler_axi_st_cmd_pkt_wr_tdata),   //   input,  width = 72,     axi_st_cmd.tdata
		.axi_st_cmd_tvalid        (scheduler_axi_st_cmd_pkt_wr_tvalid),  //   input,   width = 1,               .tvalid
		.axi_st_cmd_tready        (scheduler_axi_st_cmd_pkt_wr_tready),  //  output,   width = 1,               .tready
		.axi_st_resp_tdata        (packet_writer_axi_st_resp_tdata),     //  output,   width = 8,    axi_st_resp.tdata
		.axi_st_resp_tvalid       (packet_writer_axi_st_resp_tvalid),    //  output,   width = 1,               .tvalid
		.axi_st_resp_tready       (packet_writer_axi_st_resp_tready),    //   input,   width = 1,               .tready
		.axi_st_data_in_tdata     (snoop_axi_st_data_out_tdata),         //   input,  width = 24, axi_st_data_in.tdata
		.axi_st_data_in_tvalid    (snoop_axi_st_data_out_tvalid),        //   input,   width = 1,               .tvalid
		.axi_st_data_in_tready    (snoop_axi_st_data_out_tready),        //  output,   width = 1,               .tready
		.axi_st_data_in_tlast     (snoop_axi_st_data_out_tlast),         //   input,   width = 1,               .tlast
		.axi_st_data_in_tuser     (snoop_axi_st_data_out_tuser),         //   input,   width = 3,               .tuser
		.av_mm_master_address     (av_mm_mem_write_host_address),        //  output,  width = 32,   av_mm_master.address
		.av_mm_master_waitrequest (av_mm_mem_write_host_waitrequest),    //   input,   width = 1,               .waitrequest
		.av_mm_master_burstcount  (av_mm_mem_write_host_burstcount),     //  output,   width = 3,               .burstcount
		.av_mm_master_write       (av_mm_mem_write_host_write),          //  output,   width = 1,               .write
		.av_mm_master_writedata   (av_mm_mem_write_host_writedata),      //  output,  width = 32,               .writedata
		.mm_clk                   (1'b0),                                // (terminated),                             
		.mm_rst                   (1'b0)                                 // (terminated),                             
	);

	intel_vvp_packet_reader #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (1),
		.CLOCKS_ARE_SEPARATE    (0),
		.P_AV_MM_DATA_WIDTH     (32),
		.P_AV_MM_ADDR_WIDTH     (32),
		.BURST_TARGET           (4),
		.FIFO_DEPTH             (64),
		.PACKING_LEVEL          (1),
		.ENABLE_RESPONSES       (1),
		.DEVICE_FAMILY          ("Cyclone 10 GX")
	) packet_reader (
		.clk                        (main_clock_clk),                       //   input,   width = 1,      main_clock.clk
		.rst                        (axi_st_reset_bridge_out_reset_reset),  //   input,   width = 1,      main_reset.reset
		.axi_st_cmd_tdata           (scheduler_axi_st_cmd_pkt_rd_tdata),    //   input,  width = 72,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid          (scheduler_axi_st_cmd_pkt_rd_tvalid),   //   input,   width = 1,                .tvalid
		.axi_st_cmd_tready          (scheduler_axi_st_cmd_pkt_rd_tready),   //  output,   width = 1,                .tready
		.axi_st_resp_tdata          (packet_reader_axi_st_resp_tdata),      //  output,   width = 8,     axi_st_resp.tdata
		.axi_st_resp_tvalid         (packet_reader_axi_st_resp_tvalid),     //  output,   width = 1,                .tvalid
		.axi_st_resp_tready         (packet_reader_axi_st_resp_tready),     //   input,   width = 1,                .tready
		.axi_st_data_out_tdata      (packet_reader_axi_st_data_out_tdata),  //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid     (packet_reader_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready     (packet_reader_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast      (packet_reader_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser      (packet_reader_axi_st_data_out_tuser),  //  output,   width = 3,                .tuser
		.av_mm_master_address       (av_mm_mem_read_host_address),          //  output,  width = 32,    av_mm_master.address
		.av_mm_master_waitrequest   (av_mm_mem_read_host_waitrequest),      //   input,   width = 1,                .waitrequest
		.av_mm_master_burstcount    (av_mm_mem_read_host_burstcount),       //  output,   width = 3,                .burstcount
		.av_mm_master_read          (av_mm_mem_read_host_read),             //  output,   width = 1,                .read
		.av_mm_master_readdata      (av_mm_mem_read_host_readdata),         //   input,  width = 32,                .readdata
		.av_mm_master_readdatavalid (av_mm_mem_read_host_readdatavalid),    //   input,   width = 1,                .readdatavalid
		.mm_clk                     (1'b0),                                 // (terminated),                              
		.mm_rst                     (1'b0)                                  // (terminated),                              
	);

	system_intel_vvp_vfb_0_intel_vvp_ro_reg_servicer_2441_ylj7t2q #(
		.P_VID_PID                 (1794572855),
		.P_VERSION_NUMBER          (402981121),
		.P_AV_MM_SLAVE_ADDR_WIDTH  (7),
		.P_AV_MM_MASTER_ADDR_WIDTH (7)
	) ro_reg_servicer (
		.clk                        (main_clock_clk),                             //   input,   width = 1,   main_clock.clk
		.rst                        (axi_st_reset_bridge_out_reset_reset),        //   input,   width = 1,   main_reset.reset
		.av_mm_master_address       (ro_reg_servicer_av_mm_master_address),       //  output,   width = 7, av_mm_master.address
		.av_mm_master_waitrequest   (ro_reg_servicer_av_mm_master_waitrequest),   //   input,   width = 1,             .waitrequest
		.av_mm_master_write         (ro_reg_servicer_av_mm_master_write),         //  output,   width = 1,             .write
		.av_mm_master_writedata     (ro_reg_servicer_av_mm_master_writedata),     //  output,  width = 32,             .writedata
		.av_mm_master_byteenable    (ro_reg_servicer_av_mm_master_byteenable),    //  output,   width = 4,             .byteenable
		.av_mm_master_read          (ro_reg_servicer_av_mm_master_read),          //  output,   width = 1,             .read
		.av_mm_master_readdata      (ro_reg_servicer_av_mm_master_readdata),      //   input,  width = 32,             .readdata
		.av_mm_master_readdatavalid (ro_reg_servicer_av_mm_master_readdatavalid), //   input,   width = 1,             .readdatavalid
		.av_mm_slave_address        (av_mm_control_agent_address),                //   input,   width = 7,  av_mm_slave.address
		.av_mm_slave_write          (av_mm_control_agent_write),                  //   input,   width = 1,             .write
		.av_mm_slave_byteenable     (av_mm_control_agent_byteenable),             //   input,   width = 4,             .byteenable
		.av_mm_slave_writedata      (av_mm_control_agent_writedata),              //   input,  width = 32,             .writedata
		.av_mm_slave_read           (av_mm_control_agent_read),                   //   input,   width = 1,             .read
		.av_mm_slave_readdata       (av_mm_control_agent_readdata),               //  output,  width = 32,             .readdata
		.av_mm_slave_readdatavalid  (av_mm_control_agent_readdatavalid),          //  output,   width = 1,             .readdatavalid
		.av_mm_slave_waitrequest    (av_mm_control_agent_waitrequest)             //  output,   width = 1,             .waitrequest
	);

	system_intel_vvp_vfb_0_altera_mm_interconnect_1920_jcbczky mm_interconnect_0 (
		.ro_reg_servicer_av_mm_master_address                                      (ro_reg_servicer_av_mm_master_address),                  //   input,   width = 7,                                        ro_reg_servicer_av_mm_master.address
		.ro_reg_servicer_av_mm_master_waitrequest                                  (ro_reg_servicer_av_mm_master_waitrequest),              //  output,   width = 1,                                                                    .waitrequest
		.ro_reg_servicer_av_mm_master_byteenable                                   (ro_reg_servicer_av_mm_master_byteenable),               //   input,   width = 4,                                                                    .byteenable
		.ro_reg_servicer_av_mm_master_read                                         (ro_reg_servicer_av_mm_master_read),                     //   input,   width = 1,                                                                    .read
		.ro_reg_servicer_av_mm_master_readdata                                     (ro_reg_servicer_av_mm_master_readdata),                 //  output,  width = 32,                                                                    .readdata
		.ro_reg_servicer_av_mm_master_readdatavalid                                (ro_reg_servicer_av_mm_master_readdatavalid),            //  output,   width = 1,                                                                    .readdatavalid
		.ro_reg_servicer_av_mm_master_write                                        (ro_reg_servicer_av_mm_master_write),                    //   input,   width = 1,                                                                    .write
		.ro_reg_servicer_av_mm_master_writedata                                    (ro_reg_servicer_av_mm_master_writedata),                //   input,  width = 32,                                                                    .writedata
		.scheduler_av_mm_agent_address                                             (mm_interconnect_0_scheduler_av_mm_agent_address),       //  output,   width = 5,                                               scheduler_av_mm_agent.address
		.scheduler_av_mm_agent_write                                               (mm_interconnect_0_scheduler_av_mm_agent_write),         //  output,   width = 1,                                                                    .write
		.scheduler_av_mm_agent_read                                                (mm_interconnect_0_scheduler_av_mm_agent_read),          //  output,   width = 1,                                                                    .read
		.scheduler_av_mm_agent_readdata                                            (mm_interconnect_0_scheduler_av_mm_agent_readdata),      //   input,  width = 32,                                                                    .readdata
		.scheduler_av_mm_agent_writedata                                           (mm_interconnect_0_scheduler_av_mm_agent_writedata),     //  output,  width = 32,                                                                    .writedata
		.scheduler_av_mm_agent_byteenable                                          (mm_interconnect_0_scheduler_av_mm_agent_byteenable),    //  output,   width = 4,                                                                    .byteenable
		.scheduler_av_mm_agent_readdatavalid                                       (mm_interconnect_0_scheduler_av_mm_agent_readdatavalid), //   input,   width = 1,                                                                    .readdatavalid
		.scheduler_av_mm_agent_waitrequest                                         (mm_interconnect_0_scheduler_av_mm_agent_waitrequest),   //   input,   width = 1,                                                                    .waitrequest
		.ro_reg_servicer_av_mm_master_translator_reset_reset_bridge_in_reset_reset (axi_st_reset_bridge_out_reset_reset),                   //   input,   width = 1, ro_reg_servicer_av_mm_master_translator_reset_reset_bridge_in_reset.reset
		.axi_st_clk_bridge_out_clk_clk                                             (main_clock_clk)                                         //   input,   width = 1,                                           axi_st_clk_bridge_out_clk.clk
	);

endmodule
